export enum ViewState {
  WELCOME = 'WELCOME',
  AUTH = 'AUTH',
  COMPLETE_PROFILE = 'COMPLETE_PROFILE',
  PRIVACY = 'PRIVACY',
  HOME = 'HOME',
  PROFILE_PERSONAL = 'PROFILE_PERSONAL',
  PROFILE_PROFESSIONAL = 'PROFILE_PROFESSIONAL',
  PRODUCT_DETAIL = 'PRODUCT_DETAIL',
  SERVICE_DETAIL = 'SERVICE_DETAIL',
  VISIBILITY = 'VISIBILITY',
  CHAT = 'CHAT',
  CHAT_LIST = 'CHAT_LIST',
  MY_ITEMS = 'MY_ITEMS',
  SETTINGS = 'SETTINGS',
  NOTIFICATIONS = 'NOTIFICATIONS',
  SEARCH = 'SEARCH',
  CONTACTS = 'CONTACTS',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  UPDATE_PASSWORD = 'UPDATE_PASSWORD',
  EDIT_PROFILE = 'EDIT_PROFILE'
}

export interface User {
  id: string;
  name: string;
  avatar: string;
  location: string;
  trustScore?: number;
}
